version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/guess-game-web"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
    ignore:
      - dependency-name: "primeng"
      - dependency-name: "three"
      - dependency-name: "@types/three"
      - dependency-name: "chart.js"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
