version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/guess-game-web"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
      primeng:
        patterns:
          - "primeng"
          - "@primeuix/themes"
      three:
        patterns:
          - "three"
          - "@types/three"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
