version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/guess-game-web"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "primeng"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
